### ISSUE TITLE
Broken dependency -  read.xls is not part of gdata package anymore

### ISSUE THREAD

**Issue by vertesy** [vertesy/ReadWriter#7]
**Description**

Maybe change to `open.xlsx`?

Currently works with `gdata 2.19.0`

**Comment by erzakiev** [comment]
true, the installation of `vertesy/ReadWriter` fails with
`Error: object ‘read.xls’ is not exported by 'namespace:gdata'`

**Comment by vertesy** [comment]
### Outline

1. We need to use a new dependent package (↑↑)  to solve #6.
2. Two options are:
   3. `openxlsx::read.xlsx()`, which is used in the current `ReadWriter::write.xlsx()`
   2. `readxl::read_excel()`, whic can handle both old `xls` and new `xlsx` files, and thus preferred
4. Consequently I need to deprecate both
   1. `ReadWriter::write.xlsx()` using  `openxlsx`
   2. `ReadWriter::read.xls()` using `gdata`
   and replace both with `readxl`.

### Solution

Current `read.xls()` and `write.xlsx()` will be deprecated but kept in codebase with a warning, and they will be superseeded by `read.simple.xlsx()` and `write.simple.xlsx()`.
  
  
### Dependencies

 - many of my later functions depend on `ReadWriter::write.xlsx()`,
 - probably less/few depend on `ReadWriter::read.xls()`, but I need to confirm
  
### Issues forseen

1. `readxl` does not support `rownames` bc it returns a tibble by default.

**Comment by vertesy** [comment]
### Outline

1. We need to use a new dependent package (↑↑)  to solve #6.
2. Two options are:
   3. `openxlsx::read.xlsx()`, which is used in the current `ReadWriter::write.xlsx()`
   2. `readxl::read_excel()`, whic can handle both old `xls` and new `xlsx` files, and thus preferred
4. Consequently I need to deprecate both
   1. `ReadWriter::write.xlsx()` using  `openxlsx`
   2. `ReadWriter::read.xls()` using `gdata`
   and replace both with `readxl`.

### Solution

Current `read.xls()` and `write.xlsx()` will be deprecated but kept in codebase with a warning, and they will be superseeded by `read.simple.xlsx()` and `write.simple.xlsx()`.
  
  
### Dependencies

 - many of my later functions depend on `ReadWriter::write.xlsx()`,
 - probably less/few depend on `ReadWriter::read.xls()`, but I need to confirm
  
### Issues forseen

1. `readxl` does not support `rownames` bc it returns a tibble by default.

**Comment by vertesy** [comment]
It should also incorporate [googlesheets4](https://googlesheets4.tidyverse.org/).

**Comment by vertesy** [comment]
No, I should not use `readxl` because:

1. it only reads, so I need `writexl::write_xlsx()` and
2. `write_xlsx()` is feature-poor: you have much less control over the output preferences and formatting - something I use a lot.

So, go with: [openxlsx](https://www.rdocumentation.org/packages/openxlsx/versions/4.2.5.2) and sacrifice old `.xls` format.

**Comment by helenzhangyc** [comment]
When I was installing this package, I got the following error, seems the same as this issue? Is there any quick fix for this issue now?
```(seurat) helenz@ubuntu-shared:~/test$ Rscript -e 'devtools::install_github(repo = "vertesy/ReadWriter", upgrade = F)'
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo vertesy/ReadWriter@HEAD
── R CMD build ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/tmp/Rtmp4mLRlR/remotes2150157f6514e4/vertesy-ReadWriter-7498d13/DESCRIPTION’ ...
─  preparing ‘ReadWriter’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘ReadWriter_0.3.3.tar.gz’
   Warning: invalid uid value replaced by that for user 'nobody'
   Warning: invalid gid value replaced by that for user 'nobody'
   
* installing *source* package ‘ReadWriter’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error: object ‘read.xls’ is not exported by 'namespace:gdata'
Execution halted
ERROR: lazy loading failed for package ‘ReadWriter’
* removing ‘/homevol/helenz/miniconda3/envs/seurat/lib/R/library/ReadWriter’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/Rtmp4mLRlR/file215015d76972e/ReadWriter_0.3.3.tar.gz’ had non-zero exit status```

**Comment by vertesy** [comment]
Solved on the `read_excel` branch
